//blocks
Ace3.Local.RU("Rock Salt","Каменная соль");
//items
Ace3.Local.RU("Pie Shell","Миска для пирога");
Ace3.Local.RU("Chocolate Syrup","Шоколадный сироп");
Ace3.Local.RU("Hot Sauce","Острый соус");
Ace3.Local.RU("Coffee Cup","Кружка из-под кофе");
Ace3.Local.RU("Vanilla Extract","Экстракт ванили");
Ace3.Local.RU("Vanilla Cream","Ванильный крем");
Ace3.Local.RU("Paper Cup","Бумажный стакан");
Ace3.Local.RU("Empty Can","Пустая банка");
Ace3.Local.RU("Chocolate Syrup","Шоколадный сироп");
Ace3.Local.RU("Chocolate Ice Cream Ball","Шоколадный шарик");
Ace3.Local.RU("Vanilla Ice Cream Ball","Ванильный шарик");
Ace3.Local.RU("Strawberry Ice Cream Ball","Клубничный шарик");
Ace3.Local.RU("Glass Mug","Стеклянная кружка");

Ace3.Local.RU("Pestle & Mortar","Ступка с пестиком");
Ace3.Local.RU("Flour","Мука");
Ace3.Local.RU("Mixing Bowl","Миска для смешивания");
Ace3.Local.RU("Pot Of Water","Кастрюля с водой");
Ace3.Local.RU("Pot","Кастрюля");
Ace3.Local.RU("Salt","Соль");
Ace3.Local.RU("Pot Of Salt","Кастрюля с солью");
Ace3.Local.RU("Dough","Тесто");
Ace3.Local.RU("Chicken Bone","Куриная кость");
Ace3.Local.RU("Uncooked Stock Mix","Сырая смесь");
Ace3.Local.RU("Peeled Potato","Очищенный картофель");
Ace3.Local.RU("Bacon Joint","Беконовые связки");
Ace3.Local.RU("Intestines","Кишечник");
Ace3.Local.RU("Pork Joint","Свинные связки");
Ace3.Local.RU("Beef Joint","Говяжьи связки");
Ace3.Local.RU("Suet","Нутряное масло");
Ace3.Local.RU("Bucket Cheese","Ведро с сыром");
Ace3.Local.RU("Medium Dough Ball","Небольшой шарик теста");
Ace3.Local.RU("Mincer","Мясорубка");
Ace3.Local.RU("Uncooked Minced Meat","Сырое фаршированное мясо");
Ace3.Local.RU("Tomato Sauce","Томатный соус");
Ace3.Local.RU("Uncooked Sausage","Неприготовленная сосиска");
Ace3.Local.RU("Uncooked Bacon","Сырой бекон");
Ace3.Local.RU("Uncooked Hashbrown","Сырые оладьи");
Ace3.Local.RU("Frying Pan","Сковородка");
Ace3.Local.RU("Uncooked French Toast","Неприготовленный французский тост");
Ace3.Local.RU("Uncooked Egg In Frying Pan","Сырое яйцо в скороводке");
Ace3.Local.RU("Uncooked Mushroom In Frying Pan","Сырые грибы в скороводке");
Ace3.Local.RU("Juicer","Соковыжималка");
Ace3.Local.RU("Cooked Minced Meat","Приготовленное фаршированное мясо");
Ace3.Local.RU("Uncooked Beef Patty","Сырая говяжья котлета");
Ace3.Local.RU("Small Dough Ball","Маленький шарик теста");
Ace3.Local.RU("Cooked French Toast In Frying Pan","Приготовленный французский тост");
Ace3.Local.RU("Batter","Жидкое тесто");
Ace3.Local.RU("Uncooked Battered Fish","Сырая рыба в тесте");
Ace3.Local.RU("Peeled And Chipped Potato","Очищенный и нарезанный картофель");
Ace3.Local.RU("Uncooked Dumpling","Сырой пельмень");
Ace3.Local.RU("Uncooked Pizza","Сырая пицца");
Ace3.Local.RU("Peeled Potato In Pot","Очищенный картофель в кастрюле");
Ace3.Local.RU("Boiled Potato In Pot","Вареный картофель в кастрюле");
Ace3.Local.RU("Yorkshire Pudding In Pot","Йоркширский пуддинг в кастрюле");
Ace3.Local.RU("Stock","Сырье");
Ace3.Local.RU("Fried Egg In Frying Pan","Жареное яйцо в сковородке");
Ace3.Local.RU("Fried Mushroom In Frying Pan","Жареные грибы в сковородке");
Ace3.Local.RU("Knife","Нож");
Ace3.Local.RU("Boiled Milk","Кипяченое молоко");

//foods
Ace3.Local.RU("Tomato","Томат");
Ace3.Local.RU("Pepper","Перец");
Ace3.Local.RU("Onion","Лук");
Ace3.Local.RU("Cucumber","Огурец");
Ace3.Local.RU("Corn","Кукуруза");
Ace3.Local.RU("Lettuce","Капуста");
Ace3.Local.RU("Strawberry","Клубника");

Ace3.Local.RU("Gravy","Подливка");
Ace3.Local.RU("Yorkshire Pudding","Йоркширский пуддинг");
Ace3.Local.RU("Roast Beef Dinner","Ужин из жареной говядины");
Ace3.Local.RU("Roast Potato","Жареный картофель");
Ace3.Local.RU("Slice Of Cheese","Кусок сыра");
Ace3.Local.RU("Cheese","Сыр");
Ace3.Local.RU("Baguette","Багет");
Ace3.Local.RU("Slice Of Bread","Кусок хлеба");
Ace3.Local.RU("Footlong","Футлонг");
Ace3.Local.RU("Boiled Potato","Вареный картофель");
Ace3.Local.RU("Apple Sauce","Яблочный соус");
Ace3.Local.RU("Bacon","Бекон");
Ace3.Local.RU("Toast","Тост");
Ace3.Local.RU("Hashbrown","Оладьи");
Ace3.Local.RU("Apple Juice","Яблочный сок");
Ace3.Local.RU("Tomato Juice","Томатный сок");
Ace3.Local.RU("Carrot Juice","Морковный сок");

Ace3.Local.RU("Cooked Beef Patty","Говяжья котлета");
Ace3.Local.RU("Bacon Sandwich","Сэндвич с беконом");
Ace3.Local.RU("Butter","Масло");
Ace3.Local.RU("Battered Fish","Рыба в тесте");
Ace3.Local.RU("Pizza","Пицца");
Ace3.Local.RU("Bun","Булка");
Ace3.Local.RU("Beefburger","Бифбургер");
Ace3.Local.RU("Cheeseburger","Чизбургер");
Ace3.Local.RU("Beefstew Dumplings","Рагу из говядины с пельменями");
Ace3.Local.RU("Chips","Чипсы");
Ace3.Local.RU("Fried Egg","Жареное яйцо");
Ace3.Local.RU("Fried Mushroom","Жареный гриб");
Ace3.Local.RU("Roast Pork Dinner","Ужин из жареной свинины");
Ace3.Local.RU("Roast Mutton Dinner","Ужин из жареной баранины");
Ace3.Local.RU("Roast Rabbit Dinner","Ужин из жареной крольчатины");
Ace3.Local.RU("Chocolate","Шоколад");
Ace3.Local.RU("Double Chocolate Cookie","Двойное шоколадное печенье");
Ace3.Local.RU("Cookie Dough","Печенье");
Ace3.Local.RU("Chicken Stew","Рагу из курицы");
Ace3.Local.RU("Mutton Stew","Рагу из баранины");
Ace3.Local.RU("Pork Stew","Рагу из свинины");
Ace3.Local.RU("Sandwich BLT","Сэндвич BLT");
Ace3.Local.RU("Cheese Sandwich","Сэндвич с сыром");
Ace3.Local.RU("Cheese-Tomato Sandwich","Сэндвич из томата и сыра");
Ace3.Local.RU("Ham Sandwich","Сэндвич с ветчиной");
Ace3.Local.RU("Beef Sandwich","Сэндвич с говядиной");
Ace3.Local.RU("Chicken Sandwich","Сэндвич с курицей");
Ace3.Local.RU("Cooked French Toast","Приготовленный французский тост");
Ace3.Local.RU("Mashed Potato","Картофельное пюре");
Ace3.Local.RU("Cooked Breakfast","Приготовленный обед");
Ace3.Local.RU("Fish And Chips","Рыба с чипсами");
Ace3.Local.RU("Sausage","Колбаса");
Ace3.Local.RU("Cooked Flesh","Жареная плоть");
Ace3.Local.RU("Chopped Tomato","Нарезанный томат");
Ace3.Local.RU("Chopped Onion","Нарезанный лук");
Ace3.Local.RU("Pepper","Перец");

Ace3.Local.RU("Raw Corn","Сырая кукуруза");
Ace3.Local.RU("Raw Chicken Wing","Сырое куриное крыло");
Ace3.Local.RU("Cooked Chicken Wing","Куриное крыло");
Ace3.Local.RU("Spicy Chicken Wing","Острое куриное крыло");
Ace3.Local.RU("Cheese Pie","Сырный пирог");
Ace3.Local.RU("Cheesy Bread","Сырный хлеб");
Ace3.Local.RU("Hot Dog","Хот-Дог");
Ace3.Local.RU("Hamburger","Гамбургер");
Ace3.Local.RU("Chickenburger","Чикенбургер");
Ace3.Local.RU("Bacon Pie","Пирог с беконом");
Ace3.Local.RU("Chocolate Pie","Шоколадный пирог");
Ace3.Local.RU("Golden Apple Pie","Пирог с золотым яблоком");
Ace3.Local.RU("Fish Pie","Рыбный пирог");
Ace3.Local.RU("Cucumber Soup","Суп с огурцами");
Ace3.Local.RU("Ground Beef","Говяжий фарш");
Ace3.Local.RU("Apple Pie","Яблочный пирог");
Ace3.Local.RU("Tomato Soup","Томатный суп");
Ace3.Local.RU("Brownie","Брауни");
Ace3.Local.RU("Strawberry Pie","Клубничный пирог");
Ace3.Local.RU("Coffee","Кофе");
Ace3.Local.RU("Cappuccino","Капучино");
Ace3.Local.RU("Chocolate Cupcake","Шоколадный кекс");
Ace3.Local.RU("Strawberry Cupcake","Клубничный кекс");
Ace3.Local.RU("Crescent Roll","Круассан");
Ace3.Local.RU("Donut","Пончик");
Ace3.Local.RU("Beer","Пиво");
Ace3.Local.RU("Chicken Pot Pie","Пирог с курицей");
Ace3.Local.RU("Potato Bread","Картофельный хлеб");
Ace3.Local.RU("Pancake","Блин");
Ace3.Local.RU("Crouton","Гренок");
Ace3.Local.RU("Pumpkin Stew","Рагу из тыквы");
Ace3.Local.RU("Tortilla","Тортилья");
Ace3.Local.RU("Cheese Puff","Плавленый сыр");
Ace3.Local.RU("Waffle","Вафля");
Ace3.Local.RU("Spicy Chips","Острые чипсы");
Ace3.Local.RU("Salty Chips","Соленые чипсы");
Ace3.Local.RU("Lasagne","Лазаньи");
Ace3.Local.RU("Bucket Of Fried Chicken","Ведро с жареной курицей");
Ace3.Local.RU("Taco","Тако");
Ace3.Local.RU("Burrito","Буррито");
Ace3.Local.RU("Slice Of Pizza","Кусок пиццы");
Ace3.Local.RU("Spaghetti","Спагетти");
Ace3.Local.RU("Marshmallow","Зефир");
Ace3.Local.RU("Roasted Marshmallow","Жареный зефир");
Ace3.Local.RU("Twinkie","Твинки");
Ace3.Local.RU("Corn Bread","Кукурузный хлеб");
Ace3.Local.RU("Sugar Donut","Сахарный пончик");
Ace3.Local.RU("Chocolate Donut","Шоколадный пончик");
Ace3.Local.RU("Garden Salad","Салат с овощами");
Ace3.Local.RU("Chicken Salad","Салат с курицей");
Ace3.Local.RU("Caesar Salad",'Салат "Цезарь"');
Ace3.Local.RU("Onion Salad","Салат с луком");
Ace3.Local.RU("Taco Salad","Салат с тако");
Ace3.Local.RU("Vegetable Soup","Суп с овощами");
Ace3.Local.RU("Onion Rings","Колечки лука");
Ace3.Local.RU("Rice","Рис");
Ace3.Local.RU("Butter Rice","Рис в масле");
Ace3.Local.RU("Fried Rice","Жареный рис");
Ace3.Local.RU("Deadly Energy Drink","Отравляющий энергетический напиток");
Ace3.Local.RU("Speedy Energy Drink","Энергетический напиток скорости");
Ace3.Local.RU("Healthy Energy Drink","Энергетический напиток исцеления");
Ace3.Local.RU("Stealthy Energy Drink","Энергетический напиток незаметности");
Ace3.Local.RU("Strong Energy Drink","Энергетический напиток силы");
Ace3.Local.RU("Super Energy Drink","Суперэнергетический напиток");
Ace3.Local.RU("Ice Cream Cone","Рожок мороженого");
Ace3.Local.RU("Chocolate Ice Cream","Шоколадное мороженое");
Ace3.Local.RU("Vanilla Ice Cream","Ванильное мороженое");
Ace3.Local.RU("Strawberry Ice Cream","Клубничное мороженое");
Ace3.Local.RU("Chocolate Cookie",'Печенье с шоколадом');
Ace3.Local.RU("Chocolate Cookie Cupcake",'Кекс с шоколадным печеньем');

Ace3.Local.RU("Tomato Seeds","Семена томата");
Ace3.Local.RU("Onion Seeds","Семена лука");
Ace3.Local.RU("Lettuce Seeds","Семена капусты");
Ace3.Local.RU("Pepper Seeds","Семена перца");
Ace3.Local.RU("Corn Seeds","Семена кукурузы");
Ace3.Local.RU("Cucumber Seeds","Семена огурцов");
Ace3.Local.RU("Strawberry Seeds","Семена клубники");
Ace3.Local.RU("Rice Seeds","Семена риса");
Ace3.Local.RU("Vanilla Flower","Ванильный цветок");

Ace3.Local.RU("Chocolate Cake","Шоколадный торт");
Ace3.Local.RU("Cheese Cake","Сырный торт");
Ace3.Local.RU("Nether Cake","Торт нижнего мира");
Ace3.Local.RU("Pumpkin Cake","Тыквенный торт");
Ace3.Local.RU("Strawberry Cake","Клубничный торт");
Ace3.Local.RU("Chocolate Cookie Cake",'Шоколадный торт с печеньем');
Ace3.Local.RU("Cooked Dough","Приготовленное тесто");
Ace3.Local.RU("Bun Top","Верхняя булочка");
Ace3.Local.RU("Bun Bottom","Нижняя булочка");

Ace3.Local.RU("Salad Bowl","Салатник");
Ace3.Local.RU("Caramel Apple","Карамельное яблоко");
Ace3.Local.RU("Kebab","Кебаб");
Ace3.Local.RU("Enchilada","Энчилада");
Ace3.Local.RU("Ice Cream Sandwich","Сэндвич с мороженым");
Ace3.Local.RU("Chicken Soup","Куриный бульон");
Ace3.Local.RU("Vanilla Cupcake","Ванильный кекс");
Ace3.Local.RU("Beef Stew","Тушеная говядина");
Ace3.Local.RU("Macaroni and Cheese","Макароны с сыром");
Ace3.Local.RU("Beef Jerky","Вяленая говядина");
Ace3.Local.RU("Jambon-Beurre","Ветчина с маслом");
Ace3.Local.RU("Vanilla Donut","Пончик с ванилью");

//v1.3
Ace3.Local.RU("Futomaki","Футомаки");
Ace3.Local.RU("Uramaki","Урамаки");
Ace3.Local.RU("Rice Bread","Хлеб с рисом");
Ace3.Local.RU("Oshizushi","Прессованные суши");
Ace3.Local.RU("Ham","Ветчина");
Ace3.Local.RU("Seaweed","Водоросли");



